set tabstop=4                   " a tab is four spaces"
set softtabstop=4               " when hitting <BS>, pretend like a tab is removed, even if spaces"
set expandtab                   " expand tabs by default (overloadable per file type later)"
set shiftwidth=4                " number of spaces to use for autoindenting"
set backspace=indent,eol,start  " allow backspacing over everything in insert mode"
set autoindent                  " always set autoindenting on"
set copyindent                  " copy the previous indentation on autoindenting"
set number                      " always show line numbers"
set showmatch                   " set show matching parenthesis"
set ignorecase                  " ignore case when searching"
set smartcase                   " ignore case if search pattern is all lowercase,"
set scrolloff=4                 " keep 4 lines off the edges of the screen when scrolling"
set hlsearch                    " highlight search terms"
set incsearch                   " show search matches as you type"
set rnu
